services:
  postgres:
    image: postgres:14.0
    container_name: pg-database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=introduction
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork

volumes:
  postgres-data:
    driver: local
    
networks:
  pgnetwork:
    driver: bridge